### ISSUE TITLE
"Migrate" sr320/LabDocs to RobertsLab/LabDocs

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/2017-hackweek#10]
Transition to RobertsLab Organization repo as canonical lab repo.

**Comment by kubu4** [comment]
Decide on directory and wiki structures (e.g. what info is useful/extraneous from sr320/LabDocs).

**Comment by sr320** [comment]
Reconsider need for a "labdocs" repo...

With onboarding repo - what remains?

**Comment by sr320** [comment]
Seems complete?
