### ISSUE TITLE
Develop labelling schema for all equipment 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#11]
Stickers.
I vote for stickers. 
https://www.stickermule.com/custom-labels

**Comment by grace-ac** [comment]
All you need to do is upload an image after you pick a label shape and quantity.

Prices for sticker quantities: 
![screen shot 2017-08-08 at 1 18 57 pm](https://user-images.githubusercontent.com/14934314/29092728-2fb263e6-7c3c-11e7-8417-da5cb7b0d2eb.png)

Option for label image:
![screen shot 2017-08-08 at 1 17 24 pm](https://user-images.githubusercontent.com/14934314/29092673-0653fe24-7c3c-11e7-865c-38d062213aa4.png)

**Comment by sr320** [comment]
Nice- it would be a square? Can you design in a square format?

**Comment by grace-ac** [comment]
![label_square_1](https://user-images.githubusercontent.com/14934314/29093443-b7d14fe2-7c3e-11e7-8104-36614e2a35fa.png)

**Comment by grace-ac** [comment]
That looks weird on here, but it would be a square.

**Comment by sr320** [comment]
Print out at 2x2 so we can check

**Comment by grace-ac** [comment]
If 2x2 is too large, there's also a 1x1 option for square stickers

**Comment by grace-ac** [comment]
![screen shot 2017-08-08 at 4 00 46 pm](https://user-images.githubusercontent.com/14934314/29133086-348a3938-7ce7-11e7-90ba-beddebffd967.png)

**Comment by kubu4** [comment]
I'd like to see a different font.

**Comment by sr320** [comment]
move icon to left on small. and for upper text just include University of
Washington.

**Comment by grace-ac** [comment]
![screen shot 2017-08-09 at 10 15 36 am](https://user-images.githubusercontent.com/14934314/29134536-c5e58bea-7ceb-11e7-94d0-66d0afa3fd75.png)

**Comment by sr320** [comment]
Get Street up a line with St.
On big one, add robertslab.info under email
Maybe some different font options

**Comment by grace-ac** [comment]
![screen shot 2017-08-09 at 10 33 01 am](https://user-images.githubusercontent.com/14934314/29135250-5b0cfea4-7cee-11e7-84b8-6629d2f46d3f.png)

**Comment by kubu4** [comment]
I vote for number 5 or 6.

**Comment by sr320** [comment]
@grace-ac  is tie breaker

go ahead and order both sizes.

**Comment by grace-ac** [comment]
Oh, am I ordering these? I vote 6.

**Comment by sr320** [comment]
👍

**Comment by grace-ac** [comment]
The two new labels:

[1x1_newer.docx](https://github.com/RobertsLab/2017-hackweek/files/1229042/1x1_newer.docx)
[2x2_newer.docx](https://github.com/RobertsLab/2017-hackweek/files/1229041/2x2_newer.docx)

**Comment by grace-ac** [comment]
budget number? @sr320

**Comment by sr320** [comment]
65-2861
