### ISSUE TITLE
Add Discussion feature to notebooks

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#14]
For those notebooks where this is not currently enabled.

**Comment by sr320** [comment]
I am thinking this (instructions) needs to go into onboarding repo....

**Comment by kubu4** [comment]
Agreed. Do instructions for this exist (i.e. someone has already written how to implement for easy copy/pasting)?

**Comment by sr320** [comment]
They do
I will try to find tomorrow

**Comment by kubu4** [comment]
I guess I already sort of have this as an issue in the onboarding repo already: https://github.com/RobertsLab/onboarding/issues/1

**Comment by kubu4** [comment]
Hey! Looks like @laurahspencer did this today! Great job!

Here's a guide: https://github.com/barryclark/jekyll-now/wiki/How-to-add-Disqus-to-your-blog

Still waiting on others for compliance...
