### ISSUE TITLE
Establish off-site access to PC

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#15]
For PC with Skyline,
Make sure we have robust means to access.
TeamViewer is an option..
But maybe also RealVNC

Huskynet would likely need to be used for off-campus

**Comment by kubu4** [comment]
@laurahspencer - indicates TeamViewer doesn't start, despite being installed.

**Comment by kubu4** [comment]
@laurahspencer - TeamViewer is now installed on Woodpecker and is set up to allow unattended remote access.

However, that's all I know. I'd recommend bringing your laptop up to the lab, sitting next to Woodpecker, and attempt to connect through TeamViewer so you can see what's happening.

**Comment by laurahspencer** [comment]
Just tested on my Mac while sitting next to Woodpecker. Works great, thanks!
FYI to all: for Team Viewer to work, it needs to be perpetually on. Every time Team Viewer restarts it resets the Partner ID & PW; We should consider posting the current ID & PW somewhere accessible remotely - perhaps on the Roberts Lab Computers doc. Any opposition?

**Comment by kubu4** [comment]
- Don't close/restart TeamViewer on Woodpecker.
- If computer needs to be restarted (e.g. for updates, problems, etc.), notify lab of restart. People will then have to obtain new TeamViewer by physically sitting at Woodpecker.
- Can you add "known computers" to Woodpecker TeamViewer to avoid need for ID/password stuff?

**Comment by kubu4** [comment]
To clarify on the second point above (about sitting physically at the computer), we don't want to post the ID/password anywhere that's publicly accessible (like a Google Sheet). If it is to be shared electronically, it should be via email.

**Comment by sr320** [comment]
I am calling this resolved. Of course feel free to open new issue
