### ISSUE TITLE
Consider a podcast

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#16]

**Comment by kubu4** [comment]
@laurahspencer - Suggests paper discussions.

**Comment by sr320** [comment]
http://podcastmethod.co

**Comment by kubu4** [comment]
I saw this this morning: https://www.engadget.com/amp/2017/08/08/anchors-app-turns-your-podcasts-into-social-videos/

Could actually be useful for transcribing lab meetings...

**Comment by sr320** [comment]
Very nice..
Maybe @laurahspencer wants to take point on this?

**Comment by laurahspencer** [comment]
Sounds fun, I'm in. You mentioned this as a requirement for a grant- any restrictions on the content, audience, timelin, etc?

**Comment by sr320** [comment]
If you are in... no restriction.
Just tell us what you need.

**Comment by laurahspencer** [comment]
I'm thinking I'll start by interviewing someone from/associated with our
lab who has a recent paper, and see how that goes.

**Comment by sr320** [comment]
Awesome! 
I think we need to purchase at least two microphones. See https://github.com/RobertsLab/2017-hackweek/issues/16#issuecomment-321281821

I think audio quality is important. Each person needs microphone.

**Comment by laurahspencer** [comment]
Great, that's helpful. I'll also confer with Ian.

**Comment by sr320** [comment]
Moved to resources
