### ISSUE TITLE
Solution for bash in Jupyter Notebooks for Windows users

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/2017-hackweek#17]
Kaitlyn (and @Ellior2) have both experienced issues using bash within Jupyter Notebooks recently. I've also played around with things a bit and it seems like there's not an easy fix for this. I have a note out to the Jupyter Notebook developers on their [Gitter channel](https://gitter.im/jupyter/notebook) in hopes of gaining some clarity on what's happening and how to resolve.

However, I propose using a Docker container, and a subsequent usage guide, for Windows user wishing to run bash within a Jupyter Notebook.

I already have a Docker container (i.e. a Dockerfile) ready to go, but I think a Windows-specific Docker guide might need to be created.

**Comment by sr320** [comment]
![nty](https://media.giphy.com/media/KUOPgSNoKVcuQ/giphy.gif)

**Comment by kubu4** [comment]
Alternative is SSH and tunnel into one of the lab computers. Probably the easiest...
