### ISSUE TITLE
hummingbird update and permissions

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/2017-hackweek#18]
I realize this is not hackweek anymore, but thought this would be an appropriate place to post a few issues. 

3 things:

1. Should we update hummingbird's OS - it is still running OS X - ?

2. I've tried installing some things (e.g. coreutils) via brew and do not have permission (user: srlab). 

3. Finally, sort of unrelated, but why would this command work at the terminal but not in a jupyter notebook (using NCBI Entrez Direct, and yes I did use ! in jupyter):

esearch -db nuccore -query "Symbiodinium [ORGN] AND Symbiodinium sp. clade D [ORGN]" | efetch -format fasta > /Volumes/toaster/jdimond/Porites-astreoides-RAD/data/SymCladeD.fasta

**Comment by kubu4** [comment]
This issue was moved to RobertsLab/resources#30
