### ISSUE TITLE
redistributing purchasing efforts

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#3]

**Comment by sr320** [comment]
Can we have business amazon account where students can go in and order

**Comment by kubu4** [comment]
I believe so. I'll review Amazon business account & UW integration. Should they also be responsible for updating purchasing log and inventory for purchases they make?

**Comment by sr320** [comment]
Yes

**Comment by sr320** [comment]
integrating this into onboarding?

**Comment by kubu4** [comment]
Yes, will incorporate into onboarding.

**Comment by kubu4** [comment]
Incorporated into [resources Wiki](https://github.com/RobertsLab/resources/wiki/Purchasing).

Instructions include using SAFS purchasing request form. Using the SAFS purchasing request form allows everyone to submit purchase requests, w/o going through me. This should be the default behavior for all grad students.
