### ISSUE TITLE
Develop quality image repository

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#5]

**Comment by sr320** [comment]
Something along the lines of a Google Photos  account where AI can help search. 
mirrored on owl....

**Comment by grace-ac** [comment]
On Google-related options:

- Team Drive doesn't seem to be a good option if you want it to be public. Only members within the team will have access to the drive. No public sharing option. But images would be searchable. 

- Google photos seems to have sharing options, but no "Public" option. You have to send email invitations to people. Images are searchable. 

- Using a lab email account (I think @sr320 mentioned one exists) and create a folder in which images are uploaded. This can be made public and anyone can add photos. However, it seems that this option isn't searchable like Google photos is. Except that maybe if you know specific image names you can do the "Find" thing.

**Comment by kubu4** [comment]
I believe when you share a Google Album, you can select for it to generate a link. The behavior of the link can make the album viewable or editable by those that have the link. This would be the way to make the album public.

However, not sure what the search behavior of this implementation is like.

**Comment by grace-ac** [comment]
As far as I have been able to find, you cannot search for photos in a shared Google photos album. Lots of people are frustrated by it.

**Comment by sr320** [comment]
![ngu](http://38.media.tumblr.com/24b0cc71d05a7dcb927fb641becaba3d/tumblr_n7rp3hRMy01sx90jyo1_250.gif)

**Comment by sr320** [comment]
I suggest 
1) create a test album to evaluate features.
And 
2) create a md file in resources where everyone can go in and add link and description of their images that might be compiled at a later date.

**Comment by grace-ac** [comment]
1. link to shared google album to test features: https://goo.gl/photos/K96SpT8YGuWDnXEv8

2. link to .md file for lab images: https://github.com/RobertsLab/resources/blob/master/Project-images.md

I can keep adding the image folders i have of oyster larvae and histology if that would be useful. they can always be deleted later i know.

**Comment by sr320** [comment]
Shared google album seems very easy to join and add images, but I am not
seeing a way to search (at least from iPad).

**Comment by grace-ac** [comment]
@sr320 after reading lots of users' comments and suggestions to google for the album sharing, it appears that searching isn't possible.

**Comment by kubu4** [comment]
From poking around various forums, I'm actually under the impression that shared albums become searchable after some undetermined amount of time. Seems weird, but definitely a bunch of testimonials that seems to be the behavior.

Also, @sr320, you can't search directly in the album. You have to perform the search from the initial Google Photos interface (i.e. search ALL of your pictures/albums).

**Comment by sr320** [comment]
Seems like we need a SOP where both a list and shared album are used. Maybe histology and the sort are linked on page, whereas "usable" candid pictures are shared on album

**Comment by kubu4** [comment]
Personally, for simplicity, I think it makes the most sense to host all images on Owl or GitHub (GitHub would lack image tagging). Both of these locations are already the defacto go-to locations for data and, in my mind, would be the first places most of us would start looking to find this type of stuff.

Additionally, I don't think Google Photos will provide useful search for us; specifically for microscopy images of histology slides (or, of any microscopy). Google won't/can't identify these types of images, nor would it be able to distinguish species without an existing folder/filename/tag structure - which we can employ on Owl.

Owl also has a built-in photo viewing app (Photo Station) that provides a decent web-based GUI, if that's what's desired.

**Comment by sr320** [comment]
moved to https://github.com/RobertsLab/resources/issues/39
