### ISSUE TITLE
Name a pain-point

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#6]
List one (or more) thing you find frustrating that you imagine there might be a solution to?

**Comment by kubu4** [comment]
- Finding project-specific deets.

Propose creating (or, more active updating) of additional project-specific repos/wikis like we have for Oly genome sequencing. Useful for tracking progress, milestones, finding data and simply providing an overview of each project (i.e. who's involved, what protocols are being utilized, etc.)

**Comment by sr320** [comment]
Regarding 

> - Finding project-specific deets.

> Propose creating (or, more active updating) of additional project-specific repos/wikis like we have for Oly genome sequencing. Useful for tracking progress, milestones, finding data and simply providing an overview of each project (i.e. who's involved, what protocols are being utilized, etc.)

- maybe developing a "project template" that can be forked

- defining projects is a general challenge, but worth doing. This would keep efforts on track.
- And then somewhere simple to look to see all projects (at-a-glance)...

**Comment by kubu4** [comment]
- Tracking inventory that gets taken out of the lab (i.e. for field work, use at Manchester, etc.).

**Comment by kubu4** [comment]
From Megan - More training on GitHub usage

From @laurahspencer - Deeper Git training.

**Comment by sr320** [comment]
Two days left  for those would like resolution during hackweek

**Comment by sr320** [comment]
![dw](https://media.giphy.com/media/BHi0PMWAdEili/giphy.gif)

**Comment by sr320** [comment]
I think we are tackling most of these items elsewhere / minus git training (for which I suggest SC)
