### ISSUE TITLE
Create On-boarding Repo

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/2017-hackweek#7]
List topics that repo might address:

- [x] Lab safety (docs, links to training, links to EH&S, links to training records docs, etc)
- [x] Lab Code of Conduct
- [x] Links to lab website(s)
- [x] Links to lab documents (inventories, DMPs)
- [x] Departmental info (i.e. contact(s) for payroll, undergrad/grad student advisors, etc).

**Comment by kubu4** [comment]
[Onboarding repo created](https://github.com/RobertsLab/onboarding)

**Comment by sr320** [comment]
Resources
Examples 
https://github.com/WhitakerLab/Onboarding
https://github.com/BikLab/lab-onboarding
