### ISSUE TITLE
Create lab Code of Conduct

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/2017-hackweek#8]
Good example that can be re-used from Titus Brown: http://ivory.idyll.org/lab/coc.html

**Comment by sr320** [comment]
like going in on-boarding repo

**Comment by kubu4** [comment]
Yep. It's on the list in Issue #7 .

**Comment by kubu4** [comment]
https://github.com/RobertsLab/onboarding/wiki/Code-of-Conduct
